version: '2'
services:
  web:
    image: sebp/lighttpd
    volumes:
      - ./.build/html:/var/www/localhost/htdocs
    ports:
      - 8080:80
  sphinx:
    image: devops-wiki-sphinx
    volumes:
      - .:/opt/devops-wiki
